export const sampleHistory = [
  {
    id: "a7F9Z1",
    name: "Electronics",
    svg: "cart.svg",
  },
  {
    id: "b3C8X2",
    name: "Clothing",
    svg: "bag.svg",
  },
  {
    id: "k2P6Y9",
    name: "Books",
    svg: "box.svg",
  },
  {
    id: "d5J2W1",
    name: "Groceries",
    svg: "basket.svg",
  },
  {
    id: "g9Q4V3",
    name: "Home Decor",
    svg: "trolley.svg",
  },
  {
    id: "m1L5R7",
    name: "Toys",
    svg: "shopping-basket.svg",
  },
  {
    id: "f8K3U6",
    name: "Beauty Products",
    svg: "purse.svg",
  },
  {
    id: "n6M2T8",
    name: "Pet Supplies",
    svg: "wallet.svg",
  },
  {
    id: "p4N9S5",
    name: "Furniture",
    svg: "carton.svg",
  },
  {
    id: "q1O7R4",
    name: "Sporting Goods",
    svg: "bag-alt.svg",
  },
  {
    id: "z5H8P2",
    name: "Office Supplies",
    svg: "delivery-box.svg",
  },
  {
    id: "x3I6O9",
    name: "Electronics",
    svg: "cart.svg",
  },
  {
    id: "w9J4N8",
    name: "Clothing",
    svg: "bag.svg",
  },
  {
    id: "l7K5M6",
    name: "Books",
    svg: "box.svg",
  },
  {
    id: "r2L8J3",
    name: "Groceries",
    svg: "basket.svg",
  },
  {
    id: "s6G3I1",
    name: "Home Decor",
    svg: "trolley.svg",
  },
  {
    id: "t1H2F9",
    name: "Toys",
    svg: "shopping-basket.svg",
  },
  {
    id: "u9E7D5",
    name: "Beauty Products",
    svg: "purse.svg",
  },
  {
    id: "v4F5C8",
    name: "Pet Supplies",
    svg: "wallet.svg",
  },
  {
    id: "y8B6A3",
    name: "Furniture",
    svg: "carton.svg",
  },
  {
    id: "a7F9Z1",
    name: "Electronics",
    svg: "cart.svg",
  },
  {
    id: "b3C8X2",
    name: "Clothing",
    svg: "bag.svg",
  },
  {
    id: "k2P6Y9",
    name: "Books",
    svg: "box.svg",
  },
  {
    id: "d5J2W1",
    name: "Groceries",
    svg: "basket.svg",
  },
  {
    id: "g9Q4V3",
    name: "Home Decor",
    svg: "trolley.svg",
  },
  {
    id: "m1L5R7",
    name: "Toys",
    svg: "shopping-basket.svg",
  },
  {
    id: "f8K3U6",
    name: "Beauty Products",
    svg: "purse.svg",
  },
  {
    id: "n6M2T8",
    name: "Pet Supplies",
    svg: "wallet.svg",
  },
  {
    id: "p4N9S5",
    name: "Furniture",
    svg: "carton.svg",
  },
  {
    id: "q1O7R4",
    name: "Sporting Goods",
    svg: "bag-alt.svg",
  },
  {
    id: "z5H8P2",
    name: "Office Supplies",
    svg: "delivery-box.svg",
  },
  {
    id: "x3I6O9",
    name: "Electronics",
    svg: "cart.svg",
  },
  {
    id: "w9J4N8",
    name: "Clothing",
    svg: "bag.svg",
  },
  {
    id: "l7K5M6",
    name: "Books",
    svg: "box.svg",
  },
  {
    id: "r2L8J3",
    name: "Groceries",
    svg: "basket.svg",
  },
  {
    id: "s6G3I1",
    name: "Home Decor",
    svg: "trolley.svg",
  },
  {
    id: "t1H2F9",
    name: "Toys",
    svg: "shopping-basket.svg",
  },
  {
    id: "u9E7D5",
    name: "Beauty Products",
    svg: "purse.svg",
  },
  {
    id: "v4F5C8",
    name: "Pet Supplies",
    svg: "wallet.svg",
  },
  {
    id: "y8B6A3",
    name: "Furniture",
    svg: "carton.svg",
  },
];
export const sampleMultipleChoiceData = [
  {
    id: "1",
    question: "Where will you use this?",
    answers: [
      { text: "At Home", selected: true },
      { text: "Not At Home", selected: false },
      { text: "In Office", selected: false },
      { text: "Outside", selected: false },
    ],
    other: "",
    multipleAnswers: true,
  },

  {
    id: "2",
    question: "Where will you use this?",
    answers: [
      { text: "At Home", selected: false },
      { text: "Not At Home", selected: false },
      { text: "In Office", selected: false },
      { text: "Outside", selected: false },
    ],
    other: "",
    multipleAnswers: true,
  },
  {
    id: "3",
    question: "Where will you use this?",
    answers: [
      { text: "At Home", selected: false },
      { text: "Not At Home", selected: false },
      { text: "In Office", selected: false },
      { text: "Outside", selected: false },
    ],
    other: "",
    multipleAnswers: true,
  },
  {
    id: "4",
    question: "Where will you use this?",
    answers: [
      { text: "At Home", selected: false },
      { text: "Not At Home", selected: false },
      { text: "In Office", selected: false },
      { text: "Outside", selected: false },
    ],
    other: "",
    multipleAnswers: true,
  },
];

export const sampleHistoryObject = {
  id: "345334t5",
  name: "Coffee Grinder for Use in an Office",
  svg: "mixer.svg",
  questions: [
    {
      id: "1",
      question: "Where will you use this?",
      answers: [
        { text: "At Home", selected: true },
        { text: "Not at home", selected: false },
        { text: "In Office", selected: false },
        { text: "Outside", selected: false },
      ],
      other: "",
      multipleAnswers: false,
    },

    {
      id: "2",
      question: "Where will you use this?",
      answers: [
        { text: "At Home", selected: false },
        { text: "Not at home", selected: false },
        { text: "In Office", selected: false },
        { text: "Outside", selected: false },
      ],
      other: "string",
      multipleAnswers: true,
    },
    {
      id: "3",
      question: "Where will you use this?",
      answers: [
        { text: "At Home", selected: false },
        { text: "Not Home", selected: false },
        { text: "In Office", selected: false },
        { text: "Outside", selected: false },
      ],
      other: "string",
      multipleAnswers: true,
    },
    {
      id: "4",
      question: "Where will you use this?",
      answers: [
        { text: "At Home", selected: false },
        { text: "Not Home", selected: false },
        { text: "In Office", selected: false },
        { text: "Outside", selected: false },
      ],
      other: "string",
      multipleAnswers: true,
    },
  ],
  products: [
    {
      id: "1",
      title: 'Samsung - 55" Class TU690T Crystal UHD 4K Smart Tizen TV',
      bullets: [
        "Stream your favorite shows with Smart TV powered by Tizen",
        "Watch what you love upgraded to 4K resolution with this blazing fast processor",
        "Enjoy colors fine-tuned to how they were meant to be seen with PurColor",
        "See the dark and light in every scene to discover what HDR content delivers",
      ],
      description: null,
      reviews: [
        "Good sound quality (855)",
        "View 855 reviews about Good sound quality. 84% of the reviews are positive.",
        "Easy to use (350)",
        "View 350 reviews about Easy to use. 91% of the reviews are positive.",
        "Slow input response (213)",
        "View 213 reviews about Slow input response. 68% of the reviews are negative.",
        "Easy to set up (208)",
        "View 208 reviews about Easy to set up. 81% of the reviews are positive.",
        "Lightweight (123)",
        "View 123 reviews about Lightweight. 79% of the reviews are positive.",
        "Low quality remote (96)",
        "View 96 reviews about Low quality remote. 75% of the reviews are negative.",
        "Build quality (114)",
        "View 114 reviews about Build quality. 60% of the reviews are positive.",
        "Attractive (96)",
        "View 96 reviews about Attractive. 99% of the reviews are positive.",
        "Excessive glare (16)",
        "View 16 reviews about Excessive glare. 67% of the reviews are negative.",
        "Display quality (5)",
        "View 5 reviews about Display quality. 60% of the reviews are positive.",
        "Color vividness (3)",
        "View 3 reviews about Color vividness. 100% of the reviews are positive.",
      ],
      price: "$224.67",
      reviewScore: "4.5",
      numReviews: "13,157 reviews",
      imgLink:
        "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcSR6fEX_Cc5x_EE4JIvlmR812pAualiURuWu5eVskZNNBdYlLK5O-kj_Icc2zPdHkTmaR07qQD4YgrHlfNUr9nmFUAE685HgQ6RH-ToIRO8d4GUp8-iSdla",
    },
    {
      id: "2",
      title: 'Insignia - 40" Class LED Full HD TV',
      bullets: [
        'The 40" LED screen provides enhanced viewing experience',
        "Resolution of 1080p delivers high-quality visuals",
        "HDMI and USB ports allow reliable connectivity with compatible devices",
      ],
      description:
        'INSIGNIA- 40" CLASS LED FULL HD 1080p (Full HD) resolution 60Hz refresh rateEnhance your viewing experience with this 40-inch Insignia LED TV. The 60Hz panel refresh rate reduces motion blur for high-quality pictures, while the 1080p resolution produces stunning visuals on the LCD screen. This Insignia LED TV has HDMI and USB ports for flexible connectivity to compatible external devices, and the headphone output allows for private listening.',
      reviews: [
        "Good sound quality (1129)",
        "View 1129 reviews about Good sound quality. 82% of the reviews are positive.",
        "Lightweight (485)",
        "View 485 reviews about Lightweight. 100% of the reviews are positive.",
        "Easy to use (381)",
        "View 381 reviews about Easy to use. 97% of the reviews are positive.",
        "Easy to set up (289)",
        "View 289 reviews about Easy to set up. 89% of the reviews are positive.",
        "Build quality (255)",
        "View 255 reviews about Build quality. 56% of the reviews are positive.",
        "Fast input response (124)",
        "View 124 reviews about Fast input response. 53% of the reviews are negative.",
        "Quality remote (63)",
        "View 63 reviews about Quality remote. 72% of the reviews are positive.",
        "Attractive (61)",
        "View 61 reviews about Attractive. 98% of the reviews are positive.",
        "Low quality display (10)",
        "View 10 reviews about Low quality display. 100% of the reviews are negative.",
        "Minimal glare (5)",
        "View 5 reviews about Minimal glare. 80% of the reviews are negative.",
        "Color vividness (4)",
        "View 4 reviews about Color vividness. 100% of the reviews are positive.",
      ],
      price: "$129.99",
      reviewScore: "4.6",
      numReviews: "17,462 reviews",
      imgLink: null,
    },
    {
      id: "3",
      title: 'Insignia - 19" Class LED HD TV',
      bullets: [
        "720p resolution",
        "DTS TruSurround",
        "Supports HDMI ARC",
        "Versatile connections",
        "Parental controls",
      ],
      description:
        "Upgrade your home theater with this 19-inch Insignia LED TV. The 60Hz panel refresh rate minimizes motion blur for crisp, clear visuals, while the 720p resolution produces detailed, vibrant images on the LCD screen. This Insignia LED TV has two HDMI ports for effortless connectivity to gaming consoles and compatible devices. 18.5′′ screen (measured diagonally from corner to corner) A good size for a bedroom or dorm room. HD (720p resolution) Watch broadcast TV or your favorite content in high definition. LED TVs perform well in all lighting conditions They also deliver plasma-like deep blacks and rich colors. Advanced TV sound Two 2.5W main channel speakers. 2 HDMI inputs for the best home theater connection High-speed HDMI delivers up to 720p picture and digital surround sound in one convenient cable. HDMI cable not included. Enjoy the picture from multiple angles 178° horizontal and vertical viewing angles provide a clear picture for viewers seated near the side of the screen. 1 USB input Easily connect your digital camera or other USB device to view compatible JPEG files. Manage the viewing experience for your kids The built-in V-chip lets you block content based on program ratings and check ratings of unfamiliar programs.",
      reviews: [
        "Good sound quality (1129)",
        "View 1129 reviews about Good sound quality. 82% of the reviews are positive.",
        "Lightweight (485)",
        "View 485 reviews about Lightweight. 100% of the reviews are positive.",
        "Easy to use (381)",
        "View 381 reviews about Easy to use. 97% of the reviews are positive.",
        "Easy to set up (289)",
        "View 289 reviews about Easy to set up. 89% of the reviews are positive.",
        "Build quality (255)",
        "View 255 reviews about Build quality. 56% of the reviews are positive.",
        "Fast input response (124)",
        "View 124 reviews about Fast input response. 53% of the reviews are negative.",
        "Quality remote (63)",
        "View 63 reviews about Quality remote. 72% of the reviews are positive.",
        "Attractive (61)",
        "View 61 reviews about Attractive. 98% of the reviews are positive.",
        "Low quality display (10)",
        "View 10 reviews about Low quality display. 100% of the reviews are negative.",
        "Minimal glare (5)",
        "View 5 reviews about Minimal glare. 80% of the reviews are negative.",
        "Color vividness (4)",
        "View 4 reviews about Color vividness. 100% of the reviews are positive.",
      ],
      price: "$101.99",
      reviewScore: "4.6",
      numReviews: "17,462 reviews",
      imgLink: null,
    },
    {
      id: "4",
      title:
        'Insignia - 55" Class F30 Series LED 4K UHD Smart Fire TV NS-55F301NA22',
      bullets: [
        "Brand: INSIGNIA",
        "Color: Black",
        "Binding: Electronics",
        "model number: NS-55F301NA22",
        "Part Number: NS-55F301NA22",
        "Brand: INSIGNIA",
        "Color: Black",
        "Binding: Electronics",
        "model number: NS-55F301NA22",
        "Part Number: NS-55F301NA22",
        "Package Dimensions: 52.0 x 34.0 x 6.3 inches",
      ],
      description: null,
      reviews: [
        "Good sound quality (582)",
        "View 582 reviews about Good sound quality. 93% of the reviews are positive.",
        "Easy to use (286)",
        "View 286 reviews about Easy to use. 96% of the reviews are positive.",
        "Easy to set up (115)",
        "View 115 reviews about Easy to set up. 88% of the reviews are positive.",
        "Fast input response (114)",
        "View 114 reviews about Fast input response. 61% of the reviews are positive.",
        "Lightweight (83)",
        "View 83 reviews about Lightweight. 94% of the reviews are positive.",
        "Build quality (83)",
        "View 83 reviews about Build quality. 54% of the reviews are positive.",
        "Remote quality (58)",
        "View 58 reviews about Remote quality. 55% of the reviews are positive.",
        "Attractive (29)",
        "View 29 reviews about Attractive. 100% of the reviews are positive.",
        "Minimal glare (10)",
        "View 10 reviews about Minimal glare. 60% of the reviews are positive.",
        "Color vividness (4)",
        "View 4 reviews about Color vividness. 100% of the reviews are positive.",
        "Display quality (2)",
        "View 2 reviews about Display quality. 50% of the reviews are negative.",
      ],
      price: "$357.46",
      reviewScore: "4.6",
      numReviews: "7,021 reviews",
      imgLink:
        "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRmC5lggj_tUJjZwCwcGxH2oKkQrLojvrNho0_sTc19mYarFYw0cVyWOLuVKvK_15oQhAWzmmK91WbivZ7nyBzXEsH-DEknSR5jb6XWkSSg",
    },
    {
      id: "5",
      title: 'Samsung 85" CU7000 Crystal UHD 4K Smart TV',
      bullets: [
        "Crystal Processor With 4K UHD Upscaling.",
        "Mega Contrast.",
        "Object Trackign Sound Lite.",
        "*Q-Series and S-Series soundbars sold separately.",
        "Samsung Smart TV Hub.",
        "Crystal Processor With 4K UHD Upscaling.",
        "Mega Contrast.",
        "Object Trackign Sound Lite.",
        "*Q-Series and S-Series soundbars sold separately.",
        "Samsung Smart TV Hub.",
        "*Content services may vary by regions and are subject to change without notifications.",
        "Samsung Gaming Hub.",
        "Where gaming comes together. Stream your favorite games right from your TV. No console required.",
        "*High speed internet connection, additional gaming service subscriptions and compatible controller required.",
      ],
      description:
        "True to life color. Effortless connectivity. Dazzling 4K value. Samsung Crystal UHD is worth a look (and more). Effortlessly access TV shows, movies and ambient content using the Samsung Smart Hub, or find a range of great games on the Samsung Gaming Hub. * Enjoy content even more clear than it was created as its upgraded to 4K resolution. Color and contrast are also improved with our PurColor and Mega Contrast technologies that instantly analyze and adjust what you see on screen. As all the visual details shine through, you’ll be surrounded by 3D sound that moves with the action, engaging all your senses. *High speed internet connection, additional gaming service subscriptions and compatible controller required.",
      reviews: [
        "Good sound quality (1239)",
        "View 1239 reviews about Good sound quality. 78% of the reviews are positive.",
        "Easy to use (801)",
        "View 801 reviews about Easy to use. 89% of the reviews are positive.",
        "Fast input response (476)",
        "View 476 reviews about Fast input response. 51% of the reviews are negative.",
        "Easy to set up (320)",
        "View 320 reviews about Easy to set up. 77% of the reviews are positive.",
        "Low quality remote (281)",
        "View 281 reviews about Low quality remote. 75% of the reviews are negative.",
        "Build quality (270)",
        "View 270 reviews about Build quality. 58% of the reviews are positive.",
        "Lightweight (189)",
        "View 189 reviews about Lightweight. 85% of the reviews are positive.",
        "Attractive (192)",
        "View 192 reviews about Attractive. 100% of the reviews are positive.",
        "Excessive glare (25)",
        "View 25 reviews about Excessive glare. 68% of the reviews are negative.",
        "Display quality (12)",
        "View 12 reviews about Display quality. 67% of the reviews are positive.",
        "Color vividness (7)",
        "View 7 reviews about Color vividness. 100% of the reviews are positive.",
      ],
      price: "$1,097.99",
      reviewScore: "4.5",
      numReviews: "24,694 reviews",
      imgLink:
        "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTuMFGXpvLOuNXmGtLqs2jQeZSsn5y4Pg-FnKAM5QHea-MpNLX9XG6xaffQWoZWJY4qRA4pFPKBrFICHgMn8xVPm05aks5-rUGu9f6I1RUH",
    },
  ],
};
